# Generated by Django 4.2.16 on 2026-06-18 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0003_supplier_manufacturer"),
    ]

    state_operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Наименование клиента",
                        help_text="Название учреждения",
                        max_length=150,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        db_comment="ИНН клиента",
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True,
                        db_comment="КПП клиента",
                        max_length=12,
                        null=True,
                        verbose_name="КПП",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_comment="Телефон клиента",
                        max_length=60,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_comment="Почта клиента",
                        max_length=50,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="Адрес клиента",
                        max_length=200,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_comment="Город клиента",
                        help_text="Город клиента",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_city",
                        to="directory.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "db_table": '"medsil"."client"',
                "db_table_comment": "Таблица с перечнем клиентов. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Наименование подразделения",
                        help_text="Наименование подразделения / филиала",
                        max_length=200,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="Адрес подразделения",
                        help_text="Адрес подразделения / филиала без указания города",
                        max_length=200,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_comment="ID Города подразделения",
                        help_text="Города в котором расположено подразделение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_city",
                        to="directory.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_comment="Клиент подразделения",
                        help_text="Клиент, к которому относится подразделение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_client",
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение / Филиал",
                "verbose_name_plural": "Подразделения / Филиалы",
                "db_table": '"medsil"."department"',
                "db_table_comment": "Подразделения, филиаы клиентов.\n\n-- BMatyushin",
                "ordering": ("city",),
            },
        ),
        migrations.CreateModel(
            name="DeptContactPers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "patron",
                    models.CharField(
                        blank=True,
                        db_comment="Отчество контактного лица",
                        max_length=50,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True,
                        db_comment="Фамилия контактного лица",
                        max_length=50,
                        null=True,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Имя контактного лица",
                        max_length=50,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "mob_phone",
                    models.CharField(
                        blank=True,
                        db_comment="Мобильный телефон контактного лица",
                        help_text="Можно указать несколько",
                        max_length=60,
                        null=True,
                        verbose_name="Моб.Телефон",
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True,
                        db_comment="Можно указать несколько",
                        help_text="Можно указать несколько",
                        max_length=60,
                        null=True,
                        verbose_name="Раб.Телефон",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        db_comment="E-mail контактного лица",
                        max_length=50,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        db_comment="Комментарий контактного лица",
                        max_length=300,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Для отметки работает ли ещё контактное лицо",
                        default=True,
                        help_text="Для отметки работает ли ещё контактное лицо",
                        null=True,
                        verbose_name="Работает",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_comment="ID Подразделения",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dept_contactpers_department",
                        to="clients.department",
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        db_comment="Должность контактного лица",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dept_contactpers_position",
                        to="directory.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактное лицо подразделения",
                "verbose_name_plural": "Контактные лица подразделений",
                "db_table": '"medsil"."dept_contact_pers"',
                "db_table_comment": "Контактные лица подразделения.\n\n-- BMatyushin",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                models.F("name"), models.F("city"), name="department_name_city"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["name"], name="department_name_9f4150_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["client"], name="department_client__c5f332_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["city"], name="department_city_id_4af315_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "address")},
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["name"], name="client_name_57da18_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["inn"], name="client_inn_736c1c_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["city"], name="client_city_id_d5e2ef_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("name", "city")},
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]
