# Generated by Django 4.2.16 on 2026-07-19 06:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("directory", "0003_supplier_manufacturer"),
        ("contracts", "0005_alter_contract_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessTrip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "doc_number",
                    models.PositiveIntegerField(
                        blank=True,
                        db_comment="Номер документа (для приказа о командировке)",
                        help_text="Заполняется автоматически (max+1). Можно изменить вручную.",
                        null=True,
                        unique=True,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "beg_dt",
                    models.DateField(
                        db_comment="Дата выезда в командировку",
                        verbose_name="Дата выезда",
                    ),
                ),
                (
                    "end_dt",
                    models.DateField(
                        db_comment="Дата возвращения из командировки",
                        verbose_name="Дата возвращения",
                    ),
                ),
                (
                    "allowance_amount",
                    models.DecimalField(
                        db_comment="Сумма командировочных (суточные = дни × ставка)",
                        decimal_places=2,
                        default=Decimal("0"),
                        editable=False,
                        help_text="Считается автоматически: дни × 700 руб.",
                        max_digits=15,
                        verbose_name="Сумма командировочных",
                    ),
                ),
                (
                    "task",
                    models.TextField(
                        blank=True, verbose_name="Задание на командировку"
                    ),
                ),
                (
                    "take_with",
                    models.TextField(blank=True, verbose_name="Взять с собой"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Примечание")),
                ("report", models.TextField(blank=True, verbose_name="Отчёт")),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_comment="ID связанного договора",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_trip",
                        to="contracts.contract",
                        verbose_name="Договор",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_comment="ID сотрудника, который был в командировке",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="business_trip_employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "service_type",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Можно выбрать несколько (например, ТО и ремонт)",
                        related_name="business_trip_service_type",
                        to="directory.servicetype",
                        verbose_name="Виды работ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_comment="ID пользователя, создавшего запись",
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_trip_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем внесена запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Командировка",
                "verbose_name_plural": "Командировки",
                "db_table": '"medsil"."business_trip"',
                "db_table_comment": "Командировки сотрудников. \n\n-- Generated",
                "ordering": ("-beg_dt",),
            },
        ),
        migrations.CreateModel(
            name="ExpenseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Наименование вида затрат",
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид затрат",
                "verbose_name_plural": "Виды затрат",
                "db_table": '"medsil"."business_trip_expense_type"',
                "db_table_comment": "Справочник видов затрат на командировку. \n\n-- Generated",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BusinessTripPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        db_comment="Ссылка на фото чека",
                        upload_to="business_trip/%Y/",
                        verbose_name="Фото чека",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Когда было добавлено фото"
                    ),
                ),
                (
                    "business_trip",
                    models.ForeignKey(
                        db_comment="ID командировки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="business_trip.businesstrip",
                        verbose_name="Командировка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_comment="ID пользователя, добавившего фото",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_trip_photo_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто добавил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото чека",
                "verbose_name_plural": "Фото чеков",
                "db_table": '"medsil"."business_trip_photo"',
                "db_table_comment": "Фото чеков по командировкам. \n\n-- Generated",
            },
        ),
        migrations.CreateModel(
            name="BusinessTripExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_comment="Дата затраты", verbose_name="Дата"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_comment="Сумма затрат",
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        db_comment="На что потрачено",
                        max_length=255,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "business_trip",
                    models.ForeignKey(
                        db_comment="ID командировки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="business_trip.businesstrip",
                        verbose_name="Командировка",
                    ),
                ),
                (
                    "expense_type",
                    models.ForeignKey(
                        db_comment="ID вида затрат",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="business_trip_expense",
                        to="business_trip.expensetype",
                        verbose_name="Вид затрат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Затрата",
                "verbose_name_plural": "Затраты на поездку",
                "db_table": '"medsil"."business_trip_expense"',
                "db_table_comment": "Затраты по командировкам. \n\n-- Generated",
                "ordering": ("date",),
            },
        ),
        migrations.CreateModel(
            name="BusinessTripDestination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "beg_dt",
                    models.DateField(
                        db_comment="Дата прибытия в пункт",
                        verbose_name="Дата прибытия (с)",
                    ),
                ),
                (
                    "end_dt",
                    models.DateField(
                        db_comment="Дата выбытия из пункта",
                        verbose_name="Дата выбытия (по)",
                    ),
                ),
                (
                    "business_trip",
                    models.ForeignKey(
                        db_comment="ID командировки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="business_trip.businesstrip",
                        verbose_name="Командировка",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_comment="ID подразделения клиента",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="business_trip_destination",
                        to="clients.department",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт командировки",
                "verbose_name_plural": "Пункты командировки",
                "db_table": '"medsil"."business_trip_destination"',
                "db_table_comment": "Пункты командировки (подразделения и даты). \n\n-- Generated",
                "ordering": ("beg_dt",),
            },
        ),
        migrations.AddIndex(
            model_name="businesstrip",
            index=models.Index(
                fields=["employee"], name="business_tr_employe_842b88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businesstrip",
            index=models.Index(fields=["beg_dt"], name="business_tr_beg_dt_f74fe0_idx"),
        ),
        migrations.AddIndex(
            model_name="businesstrip",
            index=models.Index(fields=["end_dt"], name="business_tr_end_dt_b90c03_idx"),
        ),
    ]
