# Generated by Django 4.2.16 on 2026-07-19 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_trip", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesstrip",
            name="allowance_amount",
            field=models.DecimalField(
                db_comment="Сумма командировочных (суточные = дни × ставка)",
                decimal_places=2,
                default=Decimal("0"),
                editable=False,
                help_text="Дни × 700 руб.",
                max_digits=15,
                verbose_name="Сумма командировочных",
            ),
        ),
        migrations.AlterField(
            model_name="businesstripdestination",
            name="beg_dt",
            field=models.DateField(
                db_comment="Дата прибытия в пункт", verbose_name="Дата прибытия"
            ),
        ),
        migrations.AlterField(
            model_name="businesstripdestination",
            name="end_dt",
            field=models.DateField(
                db_comment="Дата выбытия из пункта", verbose_name="Дата выбытия"
            ),
        ),
    ]
