# Generated by Django 4.2.16 on 2026-07-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_trip", "0002_alter_businesstrip_allowance_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesstrip",
            name="doc_number",
            field=models.PositiveIntegerField(
                blank=True,
                db_comment="Номер документа (для приказа о командировке)",
                null=True,
                unique=True,
                verbose_name="Номер документа",
            ),
        ),
    ]
