# Generated by Django 4.2.16 on 2026-07-19 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("business_trip", "0003_alter_businesstrip_doc_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesstrip",
            name="creation_date",
            field=models.DateField(
                db_comment="Дата составления документа о командировке",
                default=django.utils.timezone.localdate,
                verbose_name="Дата составления",
            ),
        ),
    ]
