# Generated by Django 4.2.16 on 2026-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_contract_payment_status"),
        ("business_trip", "0004_businesstrip_creation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businesstrip",
            name="contract",
        ),
        migrations.AddField(
            model_name="businesstrip",
            name="contract",
            field=models.ManyToManyField(
                blank=True,
                help_text="Можно выбрать несколько контрактов",
                related_name="business_trip",
                to="contracts.contract",
                verbose_name="Контракты",
            ),
        ),
    ]
