# Generated by Django 4.2.16 on 2026-07-23 19:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_contract_payment_status"),
        ("business_trip", "0005_contract_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessTripContractExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_comment="Доля расходов командировки, отнесённая на контракт",
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "business_trip",
                    models.ForeignKey(
                        db_comment="ID командировки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_expenses",
                        to="business_trip.businesstrip",
                        verbose_name="Командировка",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        db_comment="ID контракта",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_trip_expenses",
                        to="contracts.contract",
                        verbose_name="Контракт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход командировки по контракту",
                "verbose_name_plural": "Расходы командировок по контрактам",
                "db_table": '"medsil"."business_trip_contract_expense"',
                "db_table_comment": "Доли расходов командировок по контрактам (авто). \n\n-- Generated",
                "indexes": [
                    models.Index(
                        fields=["business_trip"], name="business_tr_busines_22627e_idx"
                    ),
                    models.Index(
                        fields=["contract"], name="business_tr_contrac_99ab3f_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="businesstripcontractexpense",
            constraint=models.UniqueConstraint(
                fields=("business_trip", "contract"), name="uniq_trip_contract_expense"
            ),
        ),
    ]
