# Generated by Django 4.2.16 on 2026-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_trip", "0006_businesstripcontractexpense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesstrip",
            name="order_trip",
            field=models.CharField(
                blank=True,
                db_comment="Путь к файлу приказа о направлении работника в командировку",
                max_length=2056,
                null=True,
                verbose_name="Приказ о направлении в командировку",
            ),
        ),
    ]
