# Generated by Django 5.0.6 on 2024-08-25 18:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentAccDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Флаг, указывающий на то, что прибор установлен в подразделении клиента",
                        default=True,
                        help_text="Флаг, указывающий на то, что прибор установлен в подразделении клиента",
                        verbose_name="У клиента",
                    ),
                ),
                (
                    "install_dt",
                    models.DateField(
                        db_comment="Дата установки оборудования в подразделении клиента",
                        help_text="Дата установки оборудования в подразделении клиента",
                        null=True,
                        verbose_name="Дата монтажа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование по клиентам",
                "verbose_name_plural": "Оборудование по клиентам",
                "db_table": '"medsil"."equipment_acc_department"',
                "db_table_comment": "Учет поставленного оборудования в подразделения клиента.\n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="EquipmentAccounting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        db_comment="Серийный номер оборудования",
                        help_text="Серийный номер оборудования",
                        max_length=50,
                        verbose_name="Серийный номер",
                    ),
                ),
                (
                    "is_our_service",
                    models.BooleanField(
                        db_comment="True, если оборудование обслуживалось нами",
                        default=False,
                        verbose_name="Обслужан нами",
                    ),
                ),
                (
                    "is_our_supply",
                    models.BooleanField(
                        db_comment="True, если оборудование было поставлено нами",
                        default=True,
                        verbose_name="Поставлен нами",
                    ),
                ),
                (
                    "row_update_dt",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Дата обновления строки.",
                        help_text="Дата обновления строки. Заполняется автоматически",
                        verbose_name="Дата обновления строки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учёт оборудования",
                "verbose_name_plural": "1. Учёт оборудований",
                "db_table": '"medsil"."equipment_accounting"',
                "db_table_comment": "Таблица с учёт оборудования. Для отслеживаия оборудования по его серийному номеру.\n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Производитель оборудования",
                        help_text="Производитель оборудования",
                        max_length=150,
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        db_comment="ИНН производителя",
                        help_text="ИНН производителя",
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="Адрес производителя",
                        help_text="Адрес производителя",
                        max_length=200,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        db_comment="Контактное лицо производителя",
                        help_text="Контактное лицо производителя",
                        max_length=200,
                        null=True,
                        verbose_name="Контактное лицо",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        db_comment="Телефон производителя",
                        help_text="Контактные телефоны производителя",
                        max_length=100,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_comment="E-mail производителя",
                        max_length=100,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="True, если производитель активен",
                        default=True,
                        help_text="True, если активен. Для мягкого удаления производителя.",
                        verbose_name="Действующий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
                "db_table": '"medsil"."manufacturer"',
                "db_table_comment": "Производители оборудования. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_comment="Описание неисправности",
                        null=True,
                        verbose_name="Описание неисправности",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        db_comment="На основании чего делается ремонт",
                        help_text="На основании чего делается ремонт",
                        max_length=100,
                        null=True,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "job_content",
                    models.TextField(
                        blank=True,
                        db_comment="Содержание работ",
                        null=True,
                        verbose_name="Содержание работ",
                    ),
                ),
                (
                    "beg_dt",
                    models.DateField(
                        db_comment="Дата начала ремонта",
                        default=django.utils.timezone.now,
                        help_text="Дата начала ремонта",
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "end_dt",
                    models.DateField(
                        blank=True,
                        db_comment="Дата окончания ремонта",
                        help_text="Дата окончания ремонта",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        db_comment="Примечание, комментарии по ремонту",
                        help_text="Примечание, комментарии по ремонту",
                        null=True,
                        verbose_name="Комментарии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ремонт оборудования",
                "verbose_name_plural": "Ремонт оборудования",
                "db_table": '"medsil"."service"',
                "db_table_comment": "Учет ремонта оборудования. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Поставщик")),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="Адрес поставщика",
                        help_text="Адрес поставщика",
                        max_length=200,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        db_comment="Контактное лицо поставщика",
                        help_text="Контактное лицо поставщика",
                        max_length=200,
                        null=True,
                        verbose_name="Контактное лицо",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        db_comment="Телефон поставщика",
                        help_text="Контактные телефоны поставщика",
                        max_length=100,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_comment="E-mail поставщика",
                        max_length=100,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="True, если поставщик активен",
                        default=True,
                        help_text="True, если активен. Для мягкого удаления поставщика.",
                        verbose_name="Действующий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "db_table": '"medsil"."supplier"',
                "db_table_comment": "Поставщики оборудования. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Наименование клиента",
                        help_text="Название учреждения",
                        max_length=150,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        db_comment="ИНН клиента",
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="Адрес клиента",
                        max_length=200,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_comment="Город клиента",
                        help_text="Город клиента",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_city",
                        to="directory.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "db_table": '"medsil"."client"',
                "db_table_comment": "Таблица с перечнем клиентов. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Наименование подразделения",
                        help_text="Наименование подразделения / филиала",
                        max_length=200,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="Адрес подразделения",
                        help_text="Адрес подразделения / филиала",
                        max_length=200,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_comment="ID Города подразделения",
                        help_text="Города в котором расположено подразделение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_city",
                        to="directory.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_comment="Клиент подразделения",
                        help_text="Клиент, к которому относится подразделение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_client",
                        to="ebase.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение / Филиал",
                "verbose_name_plural": "Подразделения / Филиалы",
                "db_table": '"medsil"."department"',
                "db_table_comment": "Подразделения, филиаы клиентов.\n\n-- BMatyushin",
                "ordering": ("city",),
            },
        ),
        migrations.CreateModel(
            name="DeptContactPers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "patron",
                    models.CharField(
                        blank=True,
                        db_comment="Отчество контактного лица",
                        max_length=50,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True,
                        db_comment="Фамилия контактного лица",
                        max_length=50,
                        null=True,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Имя контактного лица",
                        max_length=50,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "mob_phone",
                    models.CharField(
                        blank=True,
                        db_comment="Мобильный телефон контактного лица",
                        help_text="Можно указать несколько",
                        max_length=60,
                        null=True,
                        verbose_name="Моб.Телефон",
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True,
                        db_comment="Можно указать несколько",
                        help_text="Можно указать несколько",
                        max_length=60,
                        null=True,
                        verbose_name="Раб.Телефон",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        db_comment="E-mail контактного лица",
                        max_length=50,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        db_comment="Комментарий контактного лица",
                        max_length=300,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Для отметки работает ли ещё контактное лицо",
                        default=True,
                        help_text="Для отметки работает ли ещё контактное лицо",
                        null=True,
                        verbose_name="Работает",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_comment="ID Подразделения",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dept_contactpers_department",
                        to="ebase.department",
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        db_comment="Должность контактного лица",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dept_contactpers_position",
                        to="directory.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактное лицо подразделения",
                "verbose_name_plural": "Контактные лица подразделений",
                "db_table": '"medsil"."dept_contact_pers"',
                "db_table_comment": "Контактные лица подразделения.\n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        db_comment="Полное наименование оборудования",
                        help_text="Полное наименование + краткое должно быть уникальным сочетанием",
                        max_length=256,
                        null=True,
                        verbose_name="Полное наименование",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        db_comment="Краткое наименование оборудования",
                        help_text="Полное наименование + краткое должно быть уникальным сочетанием",
                        max_length=50,
                        null=True,
                        verbose_name="Краткое наименование",
                    ),
                ),
                (
                    "med_direction",
                    models.ForeignKey(
                        db_comment="ID направления",
                        help_text="ID из таблицы Направления.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_med_equipment",
                        to="directory.meddirection",
                        verbose_name="Направление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мед. оборудование",
                "verbose_name_plural": "Мед. оборудование",
                "db_table": '"medsil"."equipment"',
                "db_table_comment": "Перечень моделей медициского оборудования.\n\n-- BMatyushin",
            },
        ),
    ]
