# Generated by Django 5.0.6 on 2024-08-25 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
        ("ebase", "0001_initial"),
        ("spare_part", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="spare_part",
            field=models.ManyToManyField(
                help_text="ID из таблицы Запасных частей.",
                related_name="equipment_spare_part",
                to="spare_part.sparepart",
                verbose_name="ID Запасных частей",
            ),
        ),
        migrations.AddField(
            model_name="equipmentaccdepartment",
            name="department",
            field=models.ForeignKey(
                db_comment="ID подразделения",
                help_text="Подразделение или филиал клиента",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="equipment_accounting_department_department",
                to="ebase.department",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AddField(
            model_name="equipmentaccdepartment",
            name="engineer",
            field=models.ForeignKey(
                help_text="Инженер, который запускал оборудование",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_accounting_engineer",
                to="directory.engineer",
                verbose_name="Инженер",
            ),
        ),
        migrations.AddField(
            model_name="equipmentaccounting",
            name="equipment",
            field=models.ForeignKey(
                db_comment="ID оборудования",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="equipment_accounting_equipment",
                to="ebase.equipment",
                verbose_name="Оборудования",
            ),
        ),
        migrations.AddField(
            model_name="equipmentaccounting",
            name="equipment_status",
            field=models.ForeignKey(
                db_comment="ID статуса оборудования",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_accounting_equipment_status",
                to="directory.equipmentstatus",
                verbose_name="Статус",
            ),
        ),
    ]
