# Generated by Django 5.0.6 on 2024-08-25 18:59

import directory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0002_initial"),
        ("ebase", "0002_initial"),
        ("spare_part", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentaccounting",
            name="user",
            field=models.ForeignKey(
                db_comment='Пользователь, который добавил запись в таблицу "Учёт оборудования"',
                editable=False,
                help_text='Пользователь, который добавил запись в таблицу "Учёт оборудования". Заполняется автоматически',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_accounting_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="equipmentaccdepartment",
            name="equipment_accounting",
            field=models.ForeignKey(
                db_comment="ID Учёта оборудования",
                help_text="Поставленное оборудование",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_acc_department_equipment_accounting",
                to="ebase.equipmentaccounting",
                verbose_name="Оборудование",
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_comment="Город производителя",
                default=directory.models.get_instance_city,
                help_text="Город производителя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manufacturer_city",
                to="directory.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="country",
            field=models.ForeignKey(
                db_comment="Страна производителя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manufacturer_country",
                to="directory.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="manufacturer",
            field=models.ForeignKey(
                db_comment="ID производителя",
                help_text="ID из таблицы Производителя.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_manufacturer",
                to="ebase.manufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="equipment_accounting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="service_equipment_accounting",
                to="ebase.equipmentaccounting",
                verbose_name="Оборудование для ремонта. ",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.ForeignKey(
                db_comment="ID Типа ремонта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_service_type",
                to="directory.servicetype",
                verbose_name="Типа ремонта",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="spare_part",
            field=models.ManyToManyField(
                blank=True,
                help_text="Запчасти, которые используются в ремонте. ",
                related_name="service_spare_part",
                to="spare_part.sparepart",
                verbose_name="Запчасти",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="user",
            field=models.ForeignKey(
                db_comment="ID Пользователя (сотрудника)",
                help_text='Пользователь из таблицы "Пользователи"',
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="service_company_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID Пользователя",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_comment="Город поставщика",
                default=directory.models.get_instance_city,
                help_text="Город поставщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_city",
                to="directory.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_comment="Страна производителя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_country",
                to="directory.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                db_comment="ID поставщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_supplier",
                to="ebase.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("name", "city")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                models.F("name"), models.F("city"), name="department_name_city"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "address")},
        ),
        migrations.AddIndex(
            model_name="equipmentaccounting",
            index=models.Index(fields=["serial_number"], name="serial_number_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="equipmentaccounting",
            unique_together={("serial_number", "equipment")},
        ),
        migrations.AlterUniqueTogether(
            name="manufacturer",
            unique_together={("name", "city")},
        ),
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together={("name", "city")},
        ),
        migrations.AlterUniqueTogether(
            name="equipment",
            unique_together={("full_name", "short_name")},
        ),
    ]
