# Generated by Django 5.0.6 on 2024-09-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebase", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentaccounting",
            name="url_youjail",
            field=models.URLField(
                blank=True,
                db_comment="Ссылка для связи с сервисом YouJail",
                default=None,
                help_text="Ссылка для связи с сервисом YouJail",
                max_length=2000,
                null=True,
                verbose_name="Ссылка YouJail",
            ),
        ),
    ]
