# Generated by Django 5.0.6 on 2024-11-03 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebase", "0004_equipmentaccounting_url_youjail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePhotos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        db_comment="Ссылка на поле для фото связанных с ремонтом",
                        null=True,
                        upload_to="service/%Y/",
                        verbose_name="Фото ремонта",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        db_comment="ID Ремонта",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_photos",
                        to="ebase.service",
                        verbose_name="Ремонт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото ремонта",
                "verbose_name_plural": "Фото ремонта",
                "db_table": '"medsil"."service_photos"',
                "db_table_comment": "Фотографии ремонта оборудования. \n\n-- BMatyushin",
            },
        ),
    ]
