# Generated by Django 4.2.16 on 2026-06-26 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ebase", "0010_replacementequipment_serviceaccessories_and_more"),
        ("spare_part", "0004_sparepartsupplyv2_and_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceaccessories",
            name="accessory",
            field=models.ForeignKey(
                db_comment="ID комплектующего",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_accessories_accessory",
                to="spare_part.sparepartaccessories",
                verbose_name="Комплектующее",
            ),
        ),
        migrations.AddField(
            model_name="serviceaccessories",
            name="service",
            field=models.ForeignKey(
                db_comment="ID ремонта",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_accessories",
                to="ebase.service",
                verbose_name="Ремонт",
            ),
        ),
        migrations.AddField(
            model_name="replacementequipment",
            name="accessories",
            field=models.ManyToManyField(
                blank=True,
                db_comment="ID комплектующих к прибору",
                help_text="Комплектующие, которые передаются с прибором",
                related_name="replacement_equipment_accessories",
                to="spare_part.sparepartaccessories",
                verbose_name="Комплектующие",
            ),
        ),
        migrations.AddField(
            model_name="replacementequipment",
            name="equipment",
            field=models.ForeignKey(
                db_comment="ID модели подменного оборудования",
                help_text="Модель подменного оборудования",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="replacement_equipment_equipment",
                to="ebase.equipment",
                verbose_name="Модель оборудования",
            ),
        ),
        migrations.AddField(
            model_name="replacementequipment",
            name="user",
            field=models.ForeignKey(
                db_comment="Пользователь, который добавил запись о подменном оборудовании",
                help_text="Пользователь, который добавил запись о подменном оборудовании",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacement_equipment_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="accessories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Комплектующие, используемые в ремонте",
                through="ebase.ServiceAccessories",
                to="spare_part.sparepartaccessories",
                verbose_name="Комплектующие",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="replacement_equipment",
            field=models.OneToOneField(
                blank=True,
                db_comment="ID подменного оборудования, передаваемого на время ремонта",
                help_text="Подменное оборудование, передаваемое на время ремонта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_replacement_equipment",
                to="ebase.replacementequipment",
                verbose_name="Передается на время ремонта",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceaccessories",
            unique_together={("service", "accessory")},
        ),
        migrations.AddIndex(
            model_name="replacementequipment",
            index=models.Index(
                fields=["equipment"], name="replacement_equipme_715171_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="replacementequipment",
            index=models.Index(
                fields=["serial_number"], name="replacement_serial__aad802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="replacementequipment",
            index=models.Index(fields=["state"], name="replacement_state_c3efff_idx"),
        ),
        migrations.AddIndex(
            model_name="replacementequipment",
            index=models.Index(fields=["user"], name="replacement_user_id_185f59_idx"),
        ),
    ]
