# Generated by Django 4.2.16 on 2026-06-26 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("spare_part", "0005_sync_models_with_db"),
        ("contracts", "0002_alter_contractexpense_sum"),
        ("ebase", "0010_sync_models_with_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_comment="ID контракта из реестра контрактов",
                help_text="Контракт, связанный с данным ремонтом. Один контракт может быть связан только с одним ремонтом.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service",
                to="contracts.contract",
                unique=True,
                verbose_name="Связанный Контракт",
            ),
        ),
        migrations.CreateModel(
            name="ServiceExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        db_comment="Количество запчастей, использованных в ремонте",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Кол-во",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        db_comment="Единица измерения запчасти",
                        max_length=50,
                        verbose_name="Ед. изм.",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_comment="Закупочная цена по FIFO",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Цена закупки",
                    ),
                ),
                (
                    "sum",
                    models.DecimalField(
                        db_comment="quantity * price",
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=15,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        db_comment="ID ремонта",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_expenses",
                        to="ebase.service",
                        verbose_name="Ремонт",
                    ),
                ),
                (
                    "spare_part",
                    models.ForeignKey(
                        db_comment="ID запчасти",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="service_expense_spare_part",
                        to="spare_part.sparepart",
                        verbose_name="Запчасть",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход ремонта",
                "verbose_name_plural": "Расходы ремонта",
                "db_table": '"medsil"."service_expense"',
                "db_table_comment": "Расходы на запчасти по ремонту (для аналитики).\n\n-- Generated",
                "indexes": [
                    models.Index(
                        fields=["service"], name="service_exp_service_8f7766_idx"
                    ),
                    models.Index(
                        fields=["spare_part"], name="service_exp_spare_p_503d03_idx"
                    ),
                ],
            },
        ),
    ]
