# Generated by Django 4.2.16 on 2026-06-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contractexpense_sum'),
        ('ebase', '0012_service_contract_serviceexpense'),
    ]

    operations = [
        # The service table uses a schema-qualified db_table
        # ('"medsil"."service"'). Django's PostgreSQL introspection cannot
        # resolve constraints on such tables, so AlterField alone fails to
        # DROP the column-level UNIQUE constraint (service_contract_id_key)
        # that migration 0012 created. Drop it explicitly here.
        migrations.RunSQL(
            'ALTER TABLE "medsil"."service" DROP CONSTRAINT IF EXISTS "service_contract_id_key";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='service',
            name='contract',
            field=models.ForeignKey(blank=True, db_comment='ID контракта из реестра контрактов', help_text='Контракт, связанный с данным ремонтом. На один контракт может быть несколько ремонтов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='contracts.contract', verbose_name='Связанный Контракт'),
        ),
        migrations.DeleteModel(
            name='ServiceExpense',
        ),
    ]
