# Generated by Django 4.2.16 on 2026-07-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_supplier_manufacturer'),
        ('ebase', '0013_alter_service_contract_delete_serviceexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(db_comment='ID Наименования работ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_service_type', to='directory.servicetype', verbose_name='Наименование работ'),
        ),
    ]
