# Generated by Django 4.2.16 on 2026-07-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_supplier_manufacturer'),
        ('ebase', '0014_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='engineer',
            field=models.ForeignKey(blank=True, db_comment='ID инженера', help_text='Инженер, выполняющий ремонт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_engineer', to='directory.engineer', verbose_name='Инженер'),
        ),
    ]
