# Generated by Django 5.0.6 on 2024-08-25 18:59

import directory.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
        ("ebase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePartSupply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "doc_num",
                    models.CharField(
                        db_comment="Номер документа отгрузки",
                        default="б/н",
                        help_text="Номер документа отгрузки или внутренний номер для учёта",
                        max_length=20,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "count_supply",
                    models.FloatField(
                        db_comment="Кол-во поставленой запчасти",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Кол-во",
                    ),
                ),
                (
                    "expiration_dt",
                    models.DateField(
                        blank=True,
                        db_comment="Годен до. Срок годности для запчастей со сроком годности.",
                        help_text="Срок годности для запчастей со сроком годности.",
                        null=True,
                        verbose_name="Годен до",
                    ),
                ),
                (
                    "supply_dt",
                    models.DateField(
                        db_comment="Дата поставки", verbose_name="Дата поставки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставка запчастей",
                "verbose_name_plural": "Поставки запчастей",
                "db_table": '"medsil"."spare_part_supply"',
                "db_table_comment": "Отслеживание поставок запчастей. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        db_comment="Артикул",
                        max_length=50,
                        null=True,
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Наименование запчасти",
                        max_length=300,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        db_comment="Примечание к запчасти",
                        help_text="Примечание к запчасти",
                        null=True,
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "is_expiration",
                    models.BooleanField(
                        db_comment="Отмечаются запчасти со сроками годности",
                        default=False,
                        help_text="Флаг указывающий, что у запчасти должен быть срок годности",
                        verbose_name="Срок годности",
                    ),
                ),
                (
                    "equipment",
                    models.ManyToManyField(
                        help_text="Оборудование, для которого предназначена эта запчасть. ",
                        related_name="spare_part_equipment",
                        to="ebase.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "service",
                    models.ManyToManyField(
                        help_text="В каком ремонте использовалась эта запчасть",
                        related_name="spare_part_service",
                        to="ebase.service",
                        verbose_name="ID Ремонта",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_comment="Ед.изм.",
                        default=directory.models.get_instance_unit,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="spare_part_unit",
                        to="directory.unit",
                        verbose_name="Ед.изм.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запчасть",
                "verbose_name_plural": "Запчасти",
                "db_table": '"medsil"."spare_part"',
                "db_table_comment": "Справочник запчастей. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="SparePartCount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        db_comment="Кол-во запчастей",
                        help_text="Кол-во запчастей. Заполняется автоматически",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "expiration_dt",
                    models.DateField(
                        blank=True,
                        db_comment="Годен до. Срок годности для запчастей со сроком годности.",
                        help_text="Годен до. Срок годности для запчастей со сроком годности.",
                        null=True,
                        verbose_name="Годен до",
                    ),
                ),
                (
                    "is_overdue",
                    models.BooleanField(
                        db_comment="Флаг указывающий, что запчасть просрочена",
                        default=True,
                        help_text="Флаг указывающий, что запчасть просрочена",
                        verbose_name="Не просрочено",
                    ),
                ),
                (
                    "spare_part",
                    models.ForeignKey(
                        db_comment="ID запчасти",
                        help_text="ID запчасти",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="spare_part_count_spare_part",
                        to="spare_part.sparepart",
                        verbose_name="Запчасть",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток запчастей",
                "verbose_name_plural": "Остаток запчастей",
                "db_table": '"medsil"."spare_part_count"',
                "db_table_comment": "Общее количество запчастей на остатке.\n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="SparePartShipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "doc_num",
                    models.CharField(
                        db_comment="Номер документа отгрузки",
                        default="б/н",
                        help_text="Номер документа отгрузки или внутренний номер для учёта",
                        max_length=20,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "count_shipment",
                    models.FloatField(
                        db_comment="Кол-во отгруженной запчасти",
                        help_text="Кол-во отгруженной запчасти",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Кол-во",
                    ),
                ),
                (
                    "shipment_dt",
                    models.DateField(
                        db_comment="Дата отгрузки",
                        help_text="Дата отгрузки.",
                        verbose_name="Дата отгрузки",
                    ),
                ),
                (
                    "spare_part_count",
                    models.ForeignKey(
                        db_comment="ID запчасти из таблицы spare_part_count",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spare_part_shipment_spare_part_count",
                        to="spare_part.sparepartcount",
                        verbose_name="Запчасть",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отгрузка запчастей",
                "verbose_name_plural": "Отгрузки запчастей",
                "db_table": '"medsil"."spare_part_shipment"',
                "db_table_comment": "Отслеживание отгрузок запчастей. \n\n-- BMatyushin",
            },
        ),
    ]
