# Generated by Django 5.0.6 on 2024-08-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spare_part", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepartshipment",
            name="user",
            field=models.ForeignKey(
                db_comment="ID сотрудника, который оформил отгрузку",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="spare_part_shipment_company_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто отгрузил",
            ),
        ),
        migrations.AddField(
            model_name="sparepartsupply",
            name="spare_part",
            field=models.ForeignKey(
                db_comment="ID запчасти",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spare_part_supply_spare_part",
                to="spare_part.sparepart",
                verbose_name="Запчасть",
            ),
        ),
        migrations.AddField(
            model_name="sparepartsupply",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_comment="ID сотрудника, который оформил поставку",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="spare_part_supply_company_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто добавил",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sparepart",
            unique_together={("article", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="sparepartcount",
            unique_together={("spare_part", "expiration_dt")},
        ),
    ]
