# Generated by Django 4.2.16 on 2026-06-26 16:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spare_part", "0003_quantity_to_float"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePartSupplyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        db_comment="Количество поставленной запчасти",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Кол-во",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_comment="Цена закупки за единицу",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "sum",
                    models.DecimalField(
                        db_comment="quantity * price (авто)",
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=15,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "expiration_dt",
                    models.DateField(
                        blank=True,
                        db_comment="Срок годности запчасти",
                        null=True,
                        verbose_name="Годен до",
                    ),
                ),
                ("create_dt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Запчасть поставки",
                "verbose_name_plural": "Запчасти поставки",
                "db_table": '"medsil"."spare_part_supply_item"',
                "db_table_comment": "Строки поставки запчастей с ценой и суммой.\r\n\r\n-- Generated",
            },
        ),
        migrations.CreateModel(
            name="SparePartSupplyV2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "doc_num",
                    models.CharField(
                        blank=True,
                        db_comment="Номер документа поставки",
                        max_length=255,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "supply_dt",
                    models.DateField(
                        db_comment="Дата поставки", verbose_name="Дата поставки"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        db_comment="Примечание к поставке",
                        verbose_name="Примечание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставка запчастей (v2)",
                "verbose_name_plural": "Поставки запчастей (v2)",
                "db_table": '"medsil"."spare_part_supply_v2"',
                "db_table_comment": "Обновлённая таблица поставок запчастей. Одна поставка может содержать несколько строк запчастей.\r\n\r\n-- Generated",
                "ordering": ("-supply_dt", "-create_dt"),
            },
        ),
        migrations.AddField(
            model_name="sparepartsupplyv2",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_comment="ID сотрудника, который оформил поставку",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="spare_part_supply_v2_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто добавил",
            ),
        ),
        migrations.AddField(
            model_name="sparepartsupplyitem",
            name="spare_part",
            field=models.ForeignKey(
                db_comment="ID запчасти",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="spare_part_supply_item",
                to="spare_part.sparepart",
                verbose_name="Запчасть",
            ),
        ),
        migrations.AddField(
            model_name="sparepartsupplyitem",
            name="supply",
            field=models.ForeignKey(
                db_comment="ID поставки",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="spare_part.sparepartsupplyv2",
                verbose_name="Поставка",
            ),
        ),
        migrations.AddIndex(
            model_name="sparepartsupplyv2",
            index=models.Index(
                fields=["supply_dt"], name="spare_part__supply__2858e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sparepartsupplyv2",
            index=models.Index(fields=["user"], name="spare_part__user_id_ed6039_idx"),
        ),
        migrations.AddIndex(
            model_name="sparepartsupplyitem",
            index=models.Index(
                fields=["supply"], name="spare_part__supply__0292ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sparepartsupplyitem",
            index=models.Index(
                fields=["spare_part"], name="spare_part__spare_p_cbd56c_idx"
            ),
        ),
    ]
