# Generated by Django 4.2.16 on 2026-06-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spare_part", "0005_sync_models_with_db"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sparepartsupply",
            options={
                "verbose_name": "Поставка запчастей (архив)",
                "verbose_name_plural": "Поставки запчастей (архив)",
            },
        ),
        migrations.AlterModelOptions(
            name="sparepartsupplyv2",
            options={
                "ordering": ("-supply_dt", "-create_dt"),
                "verbose_name": "Поставка запчастей",
                "verbose_name_plural": "Поставки запчастей",
            },
        ),
    ]
