# Generated by Django 4.2.16 on 2026-06-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spare_part", "0006_alter_sparepartsupply_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sparepartshipment",
            options={
                "verbose_name": "Отгрузка запчастей (архив)",
                "verbose_name_plural": "Отгрузки запчастей (архив)",
            },
        ),
    ]
