# Generated by Django 4.2.16 on 2026-06-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contractexpense_sum'),
        ('spare_part', '0007_alter_sparepartshipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartshipmentm2m',
            name='price',
            field=models.DecimalField(db_comment='Закупочная цена по FIFO', decimal_places=2, default=0, max_digits=15, verbose_name='Цена закупки'),
        ),
        migrations.AddField(
            model_name='sparepartshipmentm2m',
            name='sum',
            field=models.DecimalField(db_comment='quantity * price', decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='sparepartshipmentv2',
            name='contract',
            field=models.ForeignKey(blank=True, db_comment='Контракт, к которому относится отгрузка запчастей', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_shipments', to='contracts.contract', verbose_name='Контракт'),
        ),
    ]
