"""Test settings that run against an in-memory SQLite database.

Postgres-specific schema prefixes are stripped from generated SQL so that the
test suite can run without a local Postgres server.
"""

from .settings import *  # noqa: F401,F403

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }
}


class DisableMigrations:
    """Disable migrations so Django creates tables directly from models."""

    def __contains__(self, item):
        return True

    def __getitem__(self, item):
        return None


MIGRATION_MODULES = DisableMigrations()

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"


def _patch_schema_in_sql():
    """Strip the Postgres schema prefix from SQL generated by Django."""
    from django.db.backends.utils import CursorWrapper

    _original_execute = CursorWrapper.execute

    def _execute(self, sql, params=None):
        if isinstance(sql, str) and '"medsil"."' in sql:
            sql = sql.replace('"medsil"."', '"')
        return _original_execute(self, sql, params)

    CursorWrapper.execute = _execute


_patch_schema_in_sql()
