# Generated by Django 4.2.16 on 2026-06-26 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        db_comment="Номер контракта. Должен быть уникальным во всём реестре.",
                        max_length=255,
                        unique=True,
                        verbose_name="Номер контракта",
                    ),
                ),
                (
                    "order_number_1c",
                    models.CharField(
                        blank=True,
                        db_comment="Номер заказа в учётной системе 1С",
                        max_length=255,
                        verbose_name="Номер заказа 1С",
                    ),
                ),
                (
                    "conclusion_date",
                    models.DateField(
                        db_comment="Дата заключения контракта",
                        verbose_name="Дата заключения",
                    ),
                ),
                (
                    "service_end_date",
                    models.DateField(
                        blank=True,
                        db_comment="Дата окончания выполнения услуг по контракту",
                        null=True,
                        verbose_name="Дата окончания выполнения услуг",
                    ),
                ),
                (
                    "documentation_link",
                    models.URLField(
                        blank=True,
                        db_comment="Внешняя ссылка на документы (OneDrive/SharePoint и т.п.)",
                        verbose_name="Ссылка на документацию",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        db_comment="Период действия/отчётности, произвольный текст",
                        max_length=255,
                        verbose_name="Период",
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        db_comment="Общая сумма контракта",
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Сумма контракта",
                    ),
                ),
                (
                    "services_provided",
                    models.CharField(
                        choices=[
                            ("not_yet", "ещё нет"),
                            ("partially", "частично"),
                            ("полностью", "fully"),
                        ],
                        db_comment="Статус оказания услуг по контракту",
                        default="not_yet",
                        max_length=20,
                        verbose_name="Услуги оказаны?",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("no_receipts", "поступлений нет"),
                            ("paid", "оплачено"),
                            ("partial", "частичная оплата"),
                        ],
                        db_comment="Статус оплаты. Заполняется вручную, не выводится автоматически из суммы оплат.",
                        default="no_receipts",
                        max_length=20,
                        verbose_name="Оплата?",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        db_comment="Примечание к контракту",
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        db_comment="Сумма всех оплат по контракту (авто)",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Сумма оплат",
                    ),
                ),
                (
                    "expenses_amount",
                    models.DecimalField(
                        db_comment="Общие затраты по контракту: запчасти + командировочные/прочие (авто)",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Затраты",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        db_comment="contract_amount - payment_amount (авто)",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Долг",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        db_comment="payment_amount - expenses_amount (авто)",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Прибыль",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_comment="ID подразделения клиента",
                        help_text="Подразделение клиента, для которого заключён контракт",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="contract_client",
                        to="clients.department",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контракт",
                "verbose_name_plural": "Контракты",
                "db_table": '"medsil"."contracts_contract"',
                "db_table_comment": "Реестр контрактов отдела Сервис.\n\n-- Generated",
                "ordering": ["-conclusion_date", "-create_dt"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_comment="Дата поступления оплаты",
                        verbose_name="Дата поступления",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_comment="Сумма поступления",
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        db_comment='Примечание к оплате, например "Аванс" или номер счёта',
                        max_length=500,
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        db_comment="ID контракта",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="contracts.contract",
                        verbose_name="Контракт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплаты",
                "db_table": '"medsil"."contracts_payment"',
                "db_table_comment": "Оплаты по контрактам.\n\n-- Generated",
                "ordering": ["-date", "-create_dt"],
            },
        ),
        migrations.CreateModel(
            name="ContractExpense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("business_trip", "Командировочные"),
                            ("other", "Прочие расходы"),
                        ],
                        db_comment="Тип расхода",
                        max_length=20,
                        verbose_name="Тип расхода",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Наименование расхода. По умолчанию заполняется по типу.",
                        max_length=255,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        db_comment="Единица измерения",
                        default="шт.",
                        max_length=50,
                        verbose_name="Ед. изм.",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        db_comment="Количество",
                        decimal_places=3,
                        default=1,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Кол-во",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        db_comment="Стоимость за единицу",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "sum",
                    models.DecimalField(
                        db_comment="quantity * cost (авто)",
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        db_comment="Дата, когда расход был понесён",
                        null=True,
                        verbose_name="Дата расхода",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        db_comment="Комментарий по строке расхода",
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        db_comment="ID контракта",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="contracts.contract",
                        verbose_name="Контракт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход контракта",
                "verbose_name_plural": "Расходы контракта",
                "db_table": '"medsil"."contracts_contractexpense"',
                "db_table_comment": "Ручные расходы по контрактам (командировочные, прочие).\n\n-- Generated",
                "ordering": ["-date", "-create_dt"],
            },
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["client"], name="contracts_c_client__6ebd28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["conclusion_date"], name="contracts_c_conclus_571708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["services_provided"], name="contracts_c_service_d53c38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["payment_status"], name="contracts_c_payment_0a743f_idx"
            ),
        ),
    ]
