# Generated by Django 4.2.16 on 2026-06-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractexpense",
            name="sum",
            field=models.DecimalField(
                db_comment="quantity * cost (авто)",
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=15,
                verbose_name="Сумма",
            ),
        ),
    ]
