# Generated by Django 4.2.16 on 2026-07-04 15:48

from django.db import migrations, models
import django.db.models.deletion


def fill_client_uuid(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    target_uuid = "5777965b-657a-44e1-978e-ac105a5f8730"
    if not Client.objects.filter(id=target_uuid).exists():
        raise RuntimeError(f"Client with id {target_uuid} does not exist")
    schema_editor.execute(
        'UPDATE "medsil"."contracts_contract" SET client_id = %s;',
        [target_uuid],
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('clients', '0001_initial'),
        ('contracts', '0002_alter_contractexpense_sum'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "medsil"."contracts_contract" DROP CONSTRAINT IF EXISTS "contracts_contract_client_id_14fe7bca_fk_department_id";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(fill_client_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(
                db_comment='ID клиента',
                help_text='Клиент, для которого заключён контракт',
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='contract_client',
                to='clients.client',
                verbose_name='Клиент',
            ),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "medsil"."contracts_contract" ADD CONSTRAINT "contracts_contract_client_id_14fe7bca_fk_client_id" FOREIGN KEY ("client_id") REFERENCES "medsil"."client" ("id") DEFERRABLE INITIALLY DEFERRED;',
            reverse_sql='ALTER TABLE "medsil"."contracts_contract" DROP CONSTRAINT IF EXISTS "contracts_contract_client_id_14fe7bca_fk_client_id";',
        ),
    ]
