# Generated by Django 4.2.16 on 2026-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="documentation_link",
            field=models.CharField(
                blank=True,
                db_comment="Ссылка на папку с документацией на локальном диске",
                max_length=500,
                verbose_name="Ссылка на документацию",
            ),
        ),
    ]
