# Generated by Django 4.2.16 on 2026-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_documentation_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_status',
            field=models.CharField(choices=[('no_receipts', 'поступлений нет'), ('paid', 'оплачено'), ('partial', 'частичная оплата')], db_comment='Статус оплаты. Заполняется автоматически на основе суммы оплат и суммы контракта.', default='no_receipts', help_text='Заполняется автоматически на основе суммы оплат и суммы контракта.', max_length=20, verbose_name='Оплата?'),
        ),
    ]
