# Generated by Django 5.0.6 on 2024-08-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Страна",
                        help_text="Используется для Производителей и поставщиков",
                        max_length=50,
                        unique=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "db_table": '"medsil"."country"',
                "db_table_comment": "Таблица с перечнем стран. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Engineer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Имя инженера",
                        help_text="Имя инженера",
                        max_length=100,
                        unique=True,
                        verbose_name="Инженер",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инженер",
                "verbose_name_plural": "Инженеры",
                "db_table": '"medsil"."engineer"',
                "db_table_comment": "Инженеры. Отдельная сущность, чтобы не привязываться к пользователю в системе.\nЧерез сигнал заполняется автоматически, если у нового пользователя должность инженер.\n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="EquipmentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Статус оборудования",
                        help_text="Статус оборудования",
                        max_length=50,
                        unique=True,
                        verbose_name="Статус оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус оборудования",
                "verbose_name_plural": "Статусы оборудования",
                "db_table": '"medsil"."equipment_status"',
                "db_table_comment": "Таблица с набором статусов оборудования. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="MedDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Направление медицинского оборудования (Гематологическое, Биохимическое и т.д.)",
                        max_length=100,
                        unique=True,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "slug_name",
                    models.SlugField(
                        db_comment="Slug для названия направления мед.оборудования",
                        editable=False,
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление мед.оборудования",
                "verbose_name_plural": "Направления мед.оборудования",
                "db_table": '"medsil"."med_direction"',
                "db_table_comment": "Направления медицинского оборудования (Гематологическое, Биохимическое и т.д.).\n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Должность", max_length=50, verbose_name="Должность"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("employee", "Сотрудник"), ("client", "Клиент")],
                        db_comment="Тип должности. Cотрудник - для компании, организации. Клиент - для учреждений",
                        default="client",
                        help_text="Тип должности. Cотрудник - для компании, организации. Клиент - для учреждений",
                        max_length=50,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "db_table": '"medsil"."position"',
                "db_table_comment": "Должности сотрудников и клиентов. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Тип ремонта",
                        max_length=100,
                        unique=True,
                        verbose_name="Тип ремонта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Справочник с типом ремонта",
                "verbose_name_plural": "Справочник с типом ремонтов",
                "db_table": '"medsil"."service_type"',
                "db_table_comment": "Типы ремонтов / Виды работ. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        db_comment="Единица измерения",
                        help_text="Единица измерения",
                        max_length=50,
                        unique=True,
                        verbose_name="Сокращенное наименование",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        db_comment="Полное наименование единицы измерения",
                        help_text="Полное наименование единицы измерения",
                        max_length=100,
                        null=True,
                        verbose_name="Полное наименование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
                "db_table": '"medsil"."unit"',
                "db_table_comment": "Справочник с единицами измерения. \n\n-- BMatyushin",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Город",
                        help_text="Город",
                        max_length=50,
                        verbose_name="Город",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_comment="Регион",
                        help_text="Регион, Область в которой расположен город",
                        max_length=100,
                        null=True,
                        verbose_name="Регион",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "db_table": '"medsil"."city"',
                "db_table_comment": "Таблица с перечнем городов. \n\n-- BMatyushin",
                "unique_together": {("name", "region")},
            },
        ),
    ]
