# Generated by Django 5.0.6 on 2024-08-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="engineer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                db_comment="ID пользователя",
                help_text="Зарегистрированный пользователь системы",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="engineer_company_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь системы",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="user",
            field=models.ManyToManyField(
                related_name="position_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("name", "type")},
        ),
    ]
