# Generated by Django 4.2.16 on 2026-06-18 16:17

import directory.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_initial"),
    ]

    state_operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Поставщик")),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="Адрес поставщика",
                        help_text="Адрес поставщика",
                        max_length=200,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        db_comment="Контактное лицо поставщика",
                        help_text="Контактное лицо поставщика",
                        max_length=200,
                        null=True,
                        verbose_name="Контактное лицо",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        db_comment="Телефон поставщика",
                        help_text="Контактные телефоны поставщика",
                        max_length=100,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_comment="E-mail поставщика",
                        max_length=100,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="True, если поставщик активен",
                        default=True,
                        help_text="True, если активен. Для мягкого удаления поставщика.",
                        verbose_name="Действующий",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Город поставщика",
                        default=directory.models.get_instance_city,
                        help_text="Город поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_city",
                        to="directory.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Страна производителя",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_country",
                        to="directory.country",
                        verbose_name="Страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "db_table": '"medsil"."supplier"',
                "db_table_comment": "Поставщики оборудования. \n\n-- BMatyushin",
                "unique_together": {("name", "city")},
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID записи",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID записи",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Дата создания записи.",
                        help_text="Дата создания записи. Заполняется автоматически",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Производитель оборудования",
                        help_text="Производитель оборудования",
                        max_length=150,
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        db_comment="ИНН производителя",
                        help_text="ИНН производителя",
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_comment="Адрес производителя",
                        help_text="Адрес производителя",
                        max_length=200,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        db_comment="Контактное лицо производителя",
                        help_text="Контактное лицо производителя",
                        max_length=200,
                        null=True,
                        verbose_name="Контактное лицо",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        db_comment="Телефон производителя",
                        help_text="Контактные телефоны производителя",
                        max_length=100,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_comment="E-mail производителя",
                        max_length=100,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="True, если производитель активен",
                        default=True,
                        help_text="True, если активен. Для мягкого удаления производителя.",
                        verbose_name="Действующий",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Город производителя",
                        default=directory.models.get_instance_city,
                        help_text="Город производителя",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufacturer_city",
                        to="directory.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        db_comment="Страна производителя",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufacturer_country",
                        to="directory.country",
                        verbose_name="Страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
                "db_table": '"medsil"."manufacturer"',
                "db_table_comment": "Производители оборудования. \n\n-- BMatyushin",
                "unique_together": {("name", "city")},
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]
